name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        shell: bash
        run: |
          cd ./01_DB
          docker build . --file Dockerfile.single --tag  yemax/geo-db:24

      - name: Push docker image to docker.hub
        run: |
          docker push yemax/geo-db:24

  
  send_notification_to_telegram:
    name: Telegram push
    needs: build_image
    uses: ./.github/workflows/telegram-notification.yml
    secrets: inherit
    with:
      status: build_image.status

  send_notification_to_slack:
    name: Slack push
    needs: build_image
    uses: ./.github/workflows/slack-notification.yaml
    secrets: inherit
  
  
