name: Telegram Demo Scheduler

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.DARK_NET_TG_TOKEN }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            Олеже, як же не соромно тобі досі класти на парсер?
            

